blank_issues_enabled: false
contact_links:
  - name: Security issues
    url: https://github.com/Chethan616/Meerkat/security
    about: Help us address security issues as quickly and effectively as possible

  - name: Get latest Meerkat
    url: https://github.com/Chethan616/Meerkat/releases
    about: Your issue may be version related, so try updating first

  - name: GitHub Discussions
    url: https://github.com/Chethan616/Meerkat/discussions
    about: If you think your issue isn't that serious, you can discuss it here

  - name: Original LocalSend Project
    url: https://github.com/localsend/localsend
    about: This project is based on LocalSend (Apache 2.0). Check the original project for reference
    
